### ISSUE TITLE
:instance did not return object error on nested attributes and Mongoid

### ISSUE THREAD

**Issue by danielfarrell** [apotonick/reform#138]
Hoping someone else has run into this and could point me in the right direction.  I'm trying to use Reform with Mongoid 4 and nested fields and having a problems.

Versions:
Rails 4.0.9
Mongoid 4.0.0
Reform 1.1.1

Form looks like this:

```
class SkillsEntryForm < Reform::Form
  model :user

  property :title_other

  property :job_role_assignment do
    property :id
    property :job_role_id
    validates :job_role_id, presence: true
  end

  collection :skill_assignments do
    property :id
    property :name
    validates :name, presence: true
  end
end
```

Params look like this:

```
params[:user] = {"job_role_assignment_attributes"=>{"job_role_id"=>"5405d8f569702d31ab070000"}, "title_other"=>"", "skill_assignments_attributes"=>{"0"=>{"name"=>"MS PowerPoint Basics"}, "1"=>{"name"=>"MS Word Basics"}, "2"=>{"name"=>"MS Excel Basics"}, "3"=>{"name"=>"MS Project Basics"}, "4"=>{"name"=>"Risk Management"}, "5"=>{"name"=>"Quality Management"}, "6"=>{"name"=>"Project Management Fundamentals"}}}
```

Saving code:

```
@user = User.find ABC
@form = SkillsEntryForm.new(@user)
@form.validate(params[:user])
```

Throws the error(:instance did not return object error) with this stacktrace:

```
representable (2.0.3) lib/representable/binding.rb:166:in `instance_for'
representable (2.0.3) lib/representable/binding.rb:150:in `create_object'
representable (2.0.3) lib/representable/deserializer.rb:30:in `call'
representable (2.0.3) lib/representable/deserializer.rb:14:in `block in deserialize'
representable (2.0.3) lib/representable/deserializer.rb:11:in `each'
representable (2.0.3) lib/representable/deserializer.rb:11:in `each_with_index'
representable (2.0.3) lib/representable/deserializer.rb:11:in `each'
representable (2.0.3) lib/representable/deserializer.rb:11:in `collect'
representable (2.0.3) lib/representable/deserializer.rb:11:in `deserialize'
representable (2.0.3) lib/representable/bindings/hash_bindings.rb:44:in `deserialize'
representable (2.0.3) lib/representable/bindings/hash_bindings.rb:18:in `read'
representable (2.0.3) lib/representable/binding.rb:72:in `read_fragment_for'
representable (2.0.3) lib/representable/binding.rb:61:in `read_fragment'
representable (2.0.3) lib/representable/binding.rb:42:in `block in uncompile_fragment'
representable (2.0.3) lib/representable/binding.rb:122:in `evaluate_option'
representable (2.0.3) lib/representable/binding.rb:41:in `uncompile_fragment'
representable (2.0.3) lib/representable/mapper.rb:68:in `uncompile_fragment'
representable (2.0.3) lib/representable/mapper.rb:35:in `deserialize_property'
representable (2.0.3) lib/representable/mapper.rb:15:in `block in deserialize'
representable (2.0.3) lib/representable/mapper.rb:14:in `each'
representable (2.0.3) lib/representable/mapper.rb:14:in `deserialize'
representable (2.0.3) lib/representable.rb:34:in `update_properties_from'
representable (2.0.3) lib/representable/hash/allow_symbols.rb:10:in `update_properties_from'
representable (2.0.3) lib/representable/hash.rb:31:in `from_hash'
reform (1.1.1) lib/reform/form/validate.rb:31:in `from_hash'
reform (1.1.1) lib/reform/form/validate.rb:95:in `deserialize!'
reform (1.1.1) lib/reform/form/validate.rb:88:in `update!'
reform (1.1.1) lib/reform/form/active_model.rb:35:in `update!'
reform (1.1.1) lib/reform/form/validate.rb:80:in `validate'
reform (1.1.1) lib/reform/form/multi_parameter_attributes.rb:43:in `validate'
app/controllers/workers/skills_entry_controller.rb:13:in `block in update'
```

Any thoughts would be appreciated.

**Comment by demondzeta** [comment]
@danielfarrell  can you show me an example of how exactly did you fix this problem? (preferably code)

**Comment by danielfarrell** [comment]
Sorry @demondzeta, it's been a couple of years on this one and I don't have access to anything from that company I was working on at that time, and I don't remember what it was off the top of my head.

**Comment by apotonick** [comment]
@demondzeta This problem is completely unrelated to Mongoid. It's a insufficient populator: http://trailblazer.to/gems/reform/populator.html Come and join the Gitter channel if you need help. https://gitter.im/trailblazer/chat
