### ISSUE TITLE
"no block given" exception when some properties have prepopulation but others don't

### ISSUE THREAD

**Issue by freemanoid** [apotonick/reform#204]
When there are two properties in form, one with `prepopulate` and the other without it, I got such error (failed test stacktrace):

```
LocalJumpError: no block given
    gems/reform-1.2.6/lib/reform/form/prepopulate.rb:23:in `instance_exec'
    gems/reform-1.2.6/lib/reform/form/prepopulate.rb:23:in `block (2 levels) in prepopulate_representer'
    gems/representable-2.1.5/lib/representable/pipeline.rb:11:in `call'
    gems/representable-2.1.5/lib/representable/pipeline.rb:11:in `block in call'
    gems/representable-2.1.5/lib/representable/pipeline.rb:11:in `each'
    gems/representable-2.1.5/lib/representable/pipeline.rb:11:in `inject'
    gems/representable-2.1.5/lib/representable/pipeline.rb:11:in `call'
    gems/uber-0.0.13/lib/uber/options.rb:85:in `callable!'
    gems/uber-0.0.13/lib/uber/options.rb:70:in `evaluate_for'
    gems/uber-0.0.13/lib/uber/options.rb:60:in `evaluate'
    gems/representable-2.1.5/lib/representable/binding.rb:107:in `evaluate_option'
    gems/representable-2.1.5/lib/representable/binding.rb:71:in `render_filter'
    gems/representable-2.1.5/lib/representable/binding.rb:37:in `block in compile_fragment'
    gems/representable-2.1.5/lib/representable/binding.rb:100:in `evaluate_option'
    gems/representable-2.1.5/lib/representable/binding.rb:36:in `compile_fragment'
    gems/representable-2.1.5/lib/representable/mapper.rb:64:in `compile_fragment'
    gems/representable-2.1.5/lib/representable/mapper.rb:30:in `serialize_property'
    gems/representable-2.1.5/lib/representable/mapper.rb:22:in `block in serialize'
    gems/representable-2.1.5/lib/representable/mapper.rb:21:in `each'
    gems/representable-2.1.5/lib/representable/mapper.rb:21:in `serialize'
    gems/representable-2.1.5/lib/representable.rb:41:in `create_representation_with'
    gems/representable-2.1.5/lib/representable/hash.rb:35:in `to_hash'
    gems/reform-1.2.6/lib/reform/form/prepopulate.rb:5:in `prepopulate!'
    gems/reform-1.2.6/test/prepopulate_test.rb:12:in `block in <class:FailedTest>'
```

Here is a test to reproduce.
```ruby
class FailedTest < MiniTest::Spec
  class MyForm < Reform::Form
    collection :songs, prepopulate: ->(options){ [] } do
    end

    collection :notes do
    end
  end

  subject { MyForm.new(OpenStruct.new) }

  it { subject.prepopulate! }
end
```

**Comment by apotonick** [comment]
Hey @freemanoid this is fixed in the last commit in master! :wink:

**Comment by freemanoid** [comment]
:+1: thanks @apotonick
