### ISSUE TITLE
Problems with collections

### ISSUE THREAD

**Issue by KamilLelonek** [apotonick/reform#236]
```ruby
require 'reform'

class FormObject < Reform::Form
  def initialize
    super(Struct.new(:collection).new)
  end

  collection :collection, validates: { presence: true } do
    property :id,
      type:      String,
      validates: { presence: true }
  end
end

form_object = FormObject.new
form_object.validate({})
# => false

form_object.validate({ collection: nil })
# => representable-2.1.8/lib/representable/deserializer.rb:80:in `call':
#      undefined method `each_with_index' for nil:NilClass (NoMethodError)

form_object.validate({ collection: [] })
# => false

form_object.validate({ collection: [{}] })
# => representable-2.1.8/lib/representable/parse_strategies.rb:39:in `block in apply!':
#      undefined method `[]' for nil:NilClass (NoMethodError)

form_object.validate({ collection: [{id: nil}] })
# => representable-2.1.8/lib/representable/parse_strategies.rb:39:in `block in apply!':
#      undefined method `[]' for nil:NilClass (NoMethodError)

form_object.validate({ collection: [{id: "1"}] })
# => representable-2.1.8/lib/representable/parse_strategies.rb:39:in `block in apply!':
#      undefined method `[]' for nil:NilClass (NoMethodError)
```

**Comment by apotonick** [comment]
Please update to a higher Reform, e.g. 2.0.0.rc2, honey! :beers:

**Comment by KamilLelonek** [comment]
Bleeding edge? OK! :rocket:

**Comment by apotonick** [comment]
No, stable! :fire: :droplet: :rainbow:

**Comment by KamilLelonek** [comment]
Hm, I used `to_hash`, which is EXTREMELY useful for me, but with `2.0` it's not there anymore. What do you suggest?

**Comment by apotonick** [comment]
How did you use it? This still works when calling `#save` with a block.

**Comment by KamilLelonek** [comment]
It's weird Nick, because when I look in the source code I see that method still exists.

I'm iterating over collection elements of my form calling `to_hash` on them which gives me `NoMethodError`. When I downgrade `Reform` everything is fine.

**Comment by apotonick** [comment]
Please join IRC (Freenode) #trailblazer channel so we can sort it! :grin:

**Comment by apotonick** [comment]
I documented the solution here: http://trailblazerb.org/gems/reform/populators.html#uninitialized-collections :smile:

**Comment by pjurczynski** [comment]
I still have the issue when passing `nil` (`form_object.validate({ collection: nil })`). To overcome this I did the same what others did. I've also created a base class that I use so it's automated for all forms:

```
class ReformPatched < Reform::Form
  def validate(params)
    collections_names.each do |attribute|
      params[attribute] = [] if params[attribute].nil?
    end

    super(params)
  end

  private

  def collections_names
    self.schema.representable_attrs[:definitions].select do |_, attribute|
      attribute.instance_variable_get(:@options)[:collection]
    end.keys
  end
end
```

**Comment by apotonick** [comment]
You could simply override the setter, too.

BTW:

```ruby
schema.representable_attrs.each |dfn|
  dfn[:collection]
```

But be warned that this is private API.
