### ISSUE TITLE
Reform 2.0rc2: ActiveSupport NameError

### ISSUE THREAD

**Issue by KurtRMueller** [apotonick/reform#237]
I think it has something to do with line:
https://github.com/apotonick/reform/blob/v2.0.0.rc2/lib/reform/contract.rb#L60

After I included Reform 2.0rc2 in my Gemfile, this error started popping up. After a bit of digging, I found out this error was being thrown in the ActiveSupport 4.2.3 gem, in `lib/active_support/dependencies.rb`, line 610.

```ruby
    # Determine if the given constant has been automatically loaded.
    def autoloaded?(desc)
      return false if desc.is_a?(Module) && desc.anonymous?
      name = to_constant_name desc  # desc == Reform::Form::ActiveModel::Validations::Validator
      return false unless qualified_const_defined? name
      return autoloaded_constants.include?(name)
    end

     # line number 664
     def to_constant_name(desc) #:nodoc:
       case desc
         when String then desc.sub(/^::/, '')
         when Symbol then desc.to_s
         when Module
           desc.name ||   # desc.name == 'ba'
             raise(ArgumentError, "Anonymous modules have no name to be referenced by")
         else raise TypeError, "Not a valid constant descriptor: #{desc.inspect}"
       end
     end
```

Here's the full stack trace:

```
NameError - wrong constant name ba:
  activesupport (4.2.3) lib/active_support/core_ext/module/qualified_const.rb:30:in `block in qualified_const_defined?'
  activesupport (4.2.3) lib/active_support/core_ext/module/qualified_const.rb:29:in `qualified_const_defined?'
  activesupport (4.2.3) lib/active_support/dependencies.rb:376:in `qualified_const_defined?'
  activesupport (4.2.3) lib/active_support/dependencies.rb:610:in `autoloaded?'
  activesupport (4.2.3) lib/active_support/descendants_tracker.rb:21:in `block in clear'
  activesupport (4.2.3) lib/active_support/descendants_tracker.rb:20:in `clear'
  railties (4.2.3) lib/rails/application/finisher.rb:89:in `block (2 levels) in <module:Finisher>'
  activesupport (4.2.3) lib/active_support/file_update_checker.rb:75:in `execute'
  railties (4.2.3) lib/rails/application/finisher.rb:105:in `block (2 levels) in <module:Finisher>'
  activesupport (4.2.3) lib/active_support/callbacks.rb:444:in `block in make_lambda'
  activesupport (4.2.3) lib/active_support/callbacks.rb:190:in `block in simple'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `block in call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:502:in `call'
  activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
  actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:71:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  rack-contrib (1.3.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.3) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  request_store (1.1.0) lib/request_store/middleware.rb:8:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.3) lib/rails/engine.rb:518:in `call'
  railties (4.2.3) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  thin (1.5.1) lib/thin/connection.rb:81:in `block in pre_process'
  thin (1.5.1) lib/thin/connection.rb:79:in `pre_process'
  thin (1.5.1) lib/thin/connection.rb:54:in `process'
  thin (1.5.1) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.5) lib/eventmachine.rb:187:in `run'
  thin (1.5.1) lib/thin/backends/base.rb:63:in `start'
  thin (1.5.1) lib/thin/server.rb:159:in `start'
  rack (1.6.4) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.4) lib/rack/server.rb:286:in `start'
  railties (4.2.3) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.3) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.3) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:4:in `<main>'
```

**Comment by apotonick** [comment]
Aaah, I had this problem, too, and I think I know where it comes from.

**Comment by apotonick** [comment]
@KurtRMueller Please test the master branch. It's a problem we had years ago, ActiveModel::Naming is everywhere and requires every class to has a name, otherwise autoloading breaks - it's horrible.

Please note that I will drop ActiveModel::Validations in favour of Lotus::Validations in the next half year. AM will still work, but I don't want to support this dependency madness anymore.
