### ISSUE TITLE
form.validate raises "private method `binding' called for {}:Hash" when receiving nested hash

### ISSUE THREAD

**Issue by gertfj** [apotonick/reform#260]
I'm trying to build a form for a product which has a collection for product options using Reform 2.0.1

My problem is that any call to the ```validate(params)``` method raises the following exception when the parameter hash contains an array:

```private method `binding' called for {}:Hash```

My models looks like this:
```ruby
class Product < ActiveRecord::Base
  belongs_to :place
  
  with_options dependent: :destroy do |options|
    options.has_many :product_options
  end
end

class ProductOption < ActiveRecord::Base
  belongs_to :product
end
```

My Form looks like this:
```ruby
class CreateProductForm < ::Reform::Form
  
  # Support for simple_forms :association
  # See https://github.com/apotonick/reform/issues/122
  include ModelReflections
  
  model :product
  
  property :place_id
  property :name_en
  property :name_da
  
  validates :place_id, presence: true
  validates :name_en, presence: true
  validates :name_da, presence: true
  
  collection :product_options do
    property :name_en
    property :name_da
  end
  
end
```

I setup the model object incl. children like this:
```ruby
product = current_place.products.build(
  name_da: "Product name DA",
  name_en: "Product name en"
)

product.product_options.build(
  name_da: "Option name DA",
  name_en: "Option name EN"
)

form = CreateProductForm.new(product)
```

The following call to validate raises the exception:
```ruby
test_params_failing = {
  "place_id"=>1,
  "name_da"=>"Works DA",
  "name_en"=>"Works EN",
  "product_options"=>[
    {
      "name_en"=>"Causes failure EN",
      "name_da"=>"Causes failure DA"
    }
  ]
}

# This call raises exception
form.validate(test_params_failing)
```

The following call to validate works:
```ruby
test_params_working_without_collection = {
  "place_id"=>1,
  "name_da"=>"Works DA",
  "name_en"=>"Works EN"
}

# This call works fine
form.validate(test_params_working_without_collection)
```

The full trace for the request looks like this:
```
reform (2.0.1) lib/reform/form/populator.rb:19:in `call'
uber (0.0.13) lib/uber/options.rb:85:in `callable!'
uber (0.0.13) lib/uber/options.rb:70:in `evaluate_for'
uber (0.0.13) lib/uber/options.rb:60:in `evaluate'
representable (2.2.3) lib/representable/binding.rb:127:in `evaluate_option'
representable (2.2.3) lib/representable/deserializer.rb:75:in `instance_for'
representable (2.2.3) lib/representable/deserializer.rb:61:in `create_object'
representable (2.2.3) lib/representable/deserializer.rb:20:in `call'
representable (2.2.3) lib/representable/deserializer.rb:97:in `deserialize!'
representable (2.2.3) lib/representable/deserializer.rb:89:in `block in call'
representable (2.2.3) lib/representable/deserializer.rb:85:in `each'
representable (2.2.3) lib/representable/deserializer.rb:85:in `each_with_index'
representable (2.2.3) lib/representable/deserializer.rb:85:in `call'
representable (2.2.3) lib/representable/populator.rb:49:in `deserialize'
representable (2.2.3) lib/representable/populator.rb:21:in `call'
representable (2.2.3) lib/representable/binding.rb:85:in `read_fragment'
representable (2.2.3) lib/representable/binding.rb:64:in `block in uncompile_fragment'
representable (2.2.3) lib/representable/binding.rb:120:in `evaluate_option'
representable (2.2.3) lib/representable/binding.rb:63:in `uncompile_fragment'
representable (2.2.3) lib/representable/mapper.rb:77:in `uncompile_fragment'
representable (2.2.3) lib/representable/mapper.rb:38:in `deserialize_property'
representable (2.2.3) lib/representable/mapper.rb:18:in `block in deserialize'
representable (2.2.3) lib/representable/mapper.rb:17:in `each'
representable (2.2.3) lib/representable/mapper.rb:17:in `deserialize'
representable (2.2.3) lib/representable.rb:41:in `update_properties_from'
representable (2.2.3) lib/representable/hash/allow_symbols.rb:10:in `update_properties_from'
representable (2.2.3) lib/representable/hash.rb:31:in `from_hash'
reform (2.0.1) lib/reform/form/validate.rb:55:in `deserialize'
reform (2.0.1) lib/reform/form/validate.rb:25:in `validate'
app/services/products/create_product.rb:45:in `block in call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/transaction.rb:188:in `within_new_transaction'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
activerecord (4.2.1) lib/active_record/transactions.rb:220:in `transaction'
app/services/products/create_product.rb:22:in `call'
app/controllers/admin/products_controller.rb:43:in `create'
actionpack (4.2.1) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:198:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:117:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:505:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:92:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_process_action_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (4.2.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.2.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (4.2.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.2.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.2.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (4.2.1) lib/abstract_controller/base.rb:137:in `process'
actionview (4.2.1) lib/action_view/rendering.rb:30:in `process'
actionpack (4.2.1) lib/action_controller/metal.rb:196:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.2.1) lib/action_controller/metal.rb:237:in `block in action'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `call'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `each'
actionpack (4.2.1) lib/action_dispatch/journey/router.rb:30:in `serve'
actionpack (4.2.1) lib/action_dispatch/routing/route_set.rb:819:in `call'
bullet (4.14.7) lib/bullet/rack.rb:12:in `call'
jquery-fileupload-rails (0.4.5) lib/jquery/fileupload/rails/middleware.rb:14:in `_call'
jquery-fileupload-rails (0.4.5) lib/jquery/fileupload/rails/middleware.rb:10:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.6.1) lib/rack/etag.rb:24:in `call'
rack (1.6.1) lib/rack/conditionalget.rb:38:in `call'
rack (1.6.1) lib/rack/head.rb:13:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
rack (1.6.1) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.6.1) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
activerecord (4.2.1) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.2.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:649:in `call'
activerecord (4.2.1) lib/active_record/migration.rb:378:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `call'
activesupport (4.2.1) lib/active_support/callbacks.rb:88:in `_run_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:776:in `_run_call_callbacks'
activesupport (4.2.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (4.2.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.2.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.2.1) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.2.1) lib/rails/rack/logger.rb:20:in `call'
quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
actionpack (4.2.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.6.1) lib/rack/methodoverride.rb:22:in `call'
rack (1.6.1) lib/rack/runtime.rb:18:in `call'
activesupport (4.2.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
rack (1.6.1) lib/rack/lock.rb:17:in `call'
actionpack (4.2.1) lib/action_dispatch/middleware/static.rb:113:in `call'
rack (1.6.1) lib/rack/sendfile.rb:113:in `call'
railties (4.2.1) lib/rails/engine.rb:518:in `call'
railties (4.2.1) lib/rails/application.rb:164:in `call'
puma (2.11.3) lib/puma/rack_patch.rb:13:in `call'
puma (2.11.3) lib/puma/configuration.rb:51:in `call'
puma (2.11.3) lib/puma/server.rb:507:in `handle_request'
puma (2.11.3) lib/puma/server.rb:375:in `process_client'
puma (2.11.3) lib/puma/server.rb:262:in `block in run'
puma (2.11.3) lib/puma/thread_pool.rb:104:in `call'
puma (2.11.3) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

Any idea if this is a bug or me misunderstanding what I can call validate with?

**Comment by apotonick** [comment]
Are you sure that your `form.product_options.size == 1` and `params["product_options"].size == 1` ?

It sounds like Reform can't match incoming parameters to nested forms.

**Comment by gertfj** [comment]
Both have the size 1. As mentioned in another report I downgraded to 1.2.6 and the code works there.

**Comment by apotonick** [comment]
Aaah, sorry I'm stupid haha. Your Disposable is too new and your Reform too old. Please update to 2.0.2, that should do the trick! :laughing: :rocket:

**Comment by Titinux** [comment]
Updating to reform 2.0.2 solve the issue for me. Thanks.

**Comment by gertfj** [comment]
Very cool, I won't have time to test it before next week though. Thank you.

**Comment by apotonick** [comment]
Yeah, sorry, I removed a minor detail in Disposable and added it to Reform and then forgot to bump the dependency in Reform. :smiley:
