### ISSUE TITLE
Undefined method `represented' when using nested properties in a separate Class.

### ISSUE THREAD

**Issue by ja999** [apotonick/reform#275]
Hi!

I've encountered an issue using nesting with reform.

When I pass a `form: Song` to a nested property I get `undefined method 'represented'` error when validating this form. E.g.:
```ruby
property :song, form: SongForm, populate_if_empty: Song
```
Although, if I paste what would be found in SongForm, I get no error.

I will appreciate any help.
Thanks!

Full stack trace: 
```
NoMethodError - undefined method `represented' for #<SongForm:0x007fe5da032d08>:
  reform (2.0.1) lib/reform/form/validate.rb:73:in `block (2 levels) in deserializer'
  uber (0.0.13) lib/uber/options.rb:80:in `proc!'
  uber (0.0.13) lib/uber/options.rb:69:in `evaluate_for'
  uber (0.0.13) lib/uber/options.rb:60:in `evaluate'
  representable (2.2.3) lib/representable/binding.rb:127:in `evaluate_option'
  representable (2.2.3) lib/representable/deserializer.rb:30:in `deserialize'
  representable (2.2.3) lib/representable/deserializer.rb:23:in `call'
  representable (2.2.3) lib/representable/populator.rb:35:in `deserialize'
  representable (2.2.3) lib/representable/populator.rb:21:in `call'
  representable (2.2.3) lib/representable/binding.rb:85:in `read_fragment'
  representable (2.2.3) lib/representable/binding.rb:64:in `block in uncompile_fragment'
  representable (2.2.3) lib/representable/binding.rb:120:in `evaluate_option'
  representable (2.2.3) lib/representable/binding.rb:63:in `uncompile_fragment'
  representable (2.2.3) lib/representable/mapper.rb:77:in `uncompile_fragment'
  representable (2.2.3) lib/representable/mapper.rb:38:in `deserialize_property'
  representable (2.2.3) lib/representable/mapper.rb:18:in `block in deserialize'
  representable (2.2.3) lib/representable/mapper.rb:17:in `deserialize'
  representable (2.2.3) lib/representable.rb:41:in `update_properties_from'
  representable (2.2.3) lib/representable/hash/allow_symbols.rb:10:in `update_properties_from'
  representable (2.2.3) lib/representable/hash.rb:31:in `from_hash'
  reform (2.0.1) lib/reform/form/validate.rb:55:in `deserialize'
  reform (2.0.1) lib/reform/form/validate.rb:25:in `validate'
  app/controllers/passengers_controller.rb:8:in `create'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  bullet (4.14.7) lib/bullet/rack.rb:12:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:38:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  activerecord (4.2.0) lib/active_record/migration.rb:378:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  rack-contrib (1.3.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  web-console (2.1.2) lib/web_console/middleware.rb:37:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (2.11.3) lib/puma/server.rb:507:in `handle_request'
  puma (2.11.3) lib/puma/server.rb:375:in `process_client'
  puma (2.11.3) lib/puma/server.rb:262:in `block in run'
  puma (2.11.3) lib/puma/thread_pool.rb:104:in `block in spawn_thread'
```

**Comment by apotonick** [comment]
Please update Reform and see if the problem still exists.

**Comment by ja999** [comment]
Thanks a lot, solved. :) I was at 2.0.1. after updating to 2.0.3. the problem is no longer present.

**Comment by apotonick** [comment]
:beers:
