### ISSUE TITLE
Undefined Method validate! when destroying from collection

### ISSUE THREAD

**Issue by tlynam** [apotonick/reform#325]
When simultaneously deleting and adding to a collection, Reform consistently raises this error:

```
NoMethodError - undefined method `validate!' for nil:NilClass:
   () reform-1de909328fb8/lib/reform/contract/validate.rb:30:in `block (2 levels) in validate_nested!'
  disposable (0.2.1) lib/disposable/twin/property_processor.rb:24:in `block in collection!'
  disposable (0.2.1) lib/disposable/twin/property_processor.rb:24:in `collection!'
  disposable (0.2.1) lib/disposable/twin/property_processor.rb:15:in `call'
   () reform-1de909328fb8/lib/reform/contract/validate.rb:30:in `block in validate_nested!'
  disposable (0.2.1) lib/disposable/twin/definitions.rb:22:in `block in each'
  declarative (0.0.5) lib/declarative/definitions.rb:30:in `each'
  disposable (0.2.1) lib/disposable/twin/definitions.rb:16:in `each'
   () reform-1de909328fb8/lib/reform/contract/validate.rb:28:in `validate_nested!'
   () reform-1de909328fb8/lib/reform/contract/validate.rb:16:in `validate!'
   () reform-1de909328fb8/lib/reform/contract/validate.rb:10:in `validate'
   () reform-1de909328fb8/lib/reform/form/validate.rb:23:in `validate'
```

```ruby
class Dealer < ActiveRecord::Base
  has_many :competitors, dependent: :destroy
  accepts_nested_attributes_for :competitors, reject_if: :all_blank, allow_destroy: true
end

class Competitor < ActiveRecord::Base
  belongs_to :dealer
end

class DealerForm < Reform::Form
  include Coercion
  include Reform::Form::ActiveModel::ModelReflections
  extend Virtus::ConstMissingExtensions

  collection :competitors, skip_if: :skip_competitor? do
    property :id, type: Integer
  end

  def skip_competitor?(fragment:, **)
    if fragment["_destroy"] == "1"
      competitors.delete(competitors.find { |u| u.id.to_s == fragment["id"] })
      return true
    end
  end
end

# fails
form = DealerForm.new Dealer.new; nil
form.validate 'name' => 'a', 'aliases' => 'b',
  'competitors_attributes' => {
    '1' => {'_destroy' => '1', 'id' => 1},
    '2' => {'id' => 2}
  }

# fails
form = DealerForm.new Dealer.new; nil
form.validate 'name' => 'a', 'aliases' => 'b',
  'competitors_attributes' => {
    '1' => {'id' => 1},
    '2' => {'_destroy' => '1', 'id' => 2},
    '3' => {'id' => 3}
  }

# succeeds
form = DealerForm.new Dealer.new; nil
form.validate 'name' => 'a', 'aliases' => 'b',
  'competitors_attributes' => {
    '1' => {'id' => 1},
    '2' => {'_destroy' => '1', 'id' => 2}
  }

# succeeds
form = DealerForm.new Dealer.new; nil
form.validate 'name' => 'a', 'aliases' => 'b',
  'competitors_attributes' => {
    '1' => {'_destroy' => '1', 'id' => 1}
  }
```

**Comment by apotonick** [comment]
You're using `accepts_nested_attributes_for` and mix that with Reform and population logic. This will bring the form graph out-of-sync. Remove the nested attributes madness and remove items in your populator, as described in chapter _Mastering Forms_ of the Trailblazer book.

For sanity reasons, I do not provide support for code that contains `accepts_nested_attributes_for`.

**Comment by apotonick** [comment]
What I'm trying to say is: We're happy to help once you remove `accepts_nested_attributes_for` from your code. It's best to join https://gitter.im/trailblazer/chat for support.

**Comment by tlynam** [comment]
Thanks for your help, here's what's working while using Reform from master:

```ruby
  collection :competitors, inherit: true, populator: :competitor! do
    property :id, type: Integer
    property :name, type: String
    property :make_id, type: Integer
  end

  def competitor!(fragment:, index:, **)
    if current_competitor = competitors.find { |c| c.id.to_s == fragment["id"] }
      if fragment["_destroy"] == "1"
        competitors.delete(current_competitor)
        return Representable::Pipeline::Stop
      else
        current_competitor
      end
    else
      competitors.insert(index, T1000::Competitor.new)
    end
  end
```

**Comment by apotonick** [comment]
Legend! Thanks! :smile:

**Comment by tlynam** [comment]
Sorry I spoke too soon.  I have this error still.  I was able to resolve with a patch.  I must have forgotten to restart rails while testing and thought I didn't need it.

I updated this line to include `compact` https://github.com/apotonick/disposable/blob/master/lib/disposable/twin/property_processor.rb#L24
to `@value.compact`

```
NoMethodError - undefined method `validate!' for nil:NilClass:
   /gems/reform-1de909328fb8/lib/reform/contract/validate.rb:30:in `block (2 levels) in validate_nested!'
  disposable (0.2.1) lib/disposable/twin/property_processor.rb:24:in `block in collection!'
  disposable (0.2.1) lib/disposable/twin/property_processor.rb:24:in `collection!'
  disposable (0.2.1) lib/disposable/twin/property_processor.rb:15:in `call'
   /gems/reform-1de909328fb8/lib/reform/contract/validate.rb:30:in `block in validate_nested!'
  disposable (0.2.1) lib/disposable/twin/definitions.rb:22:in `block in each'
  declarative (0.0.5) lib/declarative/definitions.rb:30:in `each'
  disposable (0.2.1) lib/disposable/twin/definitions.rb:16:in `each'
   /gems/reform-1de909328fb8/lib/reform/contract/validate.rb:28:in `validate_nested!'
   /gems/reform-1de909328fb8/lib/reform/contract/validate.rb:16:in `validate!'
   /gems/reform-1de909328fb8/lib/reform/contract/validate.rb:10:in `validate'
   /gems/reform-1de909328fb8/lib/reform/form/validate.rb:23:in `validate'
  app/forms/dealer_form.rb:62:in `validate'
```

**Comment by apotonick** [comment]
The problem is you use `insert` with the `index`, and that creates an array out of sync.

Can you try changing 

```ruby
competitors.insert(index, T1000::Competitor.new)
```

to


```ruby
competitors.insert(competitors.size, T1000::Competitor.new)
```

**Comment by tlynam** [comment]
Thanks a lot!  btw, I think we need to return `twin` here so we can use `<<` instead of `insert`
https://github.com/apotonick/disposable/blob/master/lib/disposable/twin/collection.rb#L21
Can I create a pr?

**Comment by apotonick** [comment]
You can try, but you won't be able to change Ruby's `<<` semantics!!! :grimacing: 

What we need is an `append` in Disposabble. PR yo!

**Comment by apotonick** [comment]
Too late! https://github.com/apotonick/disposable/commit/bf8c07b2d5e8d98f33837db86816c889993556bc

**Comment by tlynam** [comment]
Man, I need to be faster!

**Comment by tlynam** [comment]
Do you think the comment in the << implementation is incorrect?  Here's an example where the array is returned instead of the object being inserted.

```ruby
>> a = []
=> []
>> a << 3
=> [3]
```

**Comment by apotonick** [comment]
Yepp, the semantic for `#<<` is "incorrect" for the populator because it always has to return the form that represents the currently processed fragment.

Hey, good news! I documented this (so you don't need to buy the Trailblazer book :tired_face: ): http://trailblazer.to/gems/reform/populator.html#populator-collections
