### ISSUE TITLE
Failed to process hash fields

### ISSUE THREAD

**Issue by sorrat** [apotonick/reform#341]
Failed to process hash with nested hashes with fake empty model, e.g. `OpenStruct`.
I tried to `include Struct` as suggested at [reform docs](http://trailblazer.to/gems/reform/#hash-fields), but without luck.

```ruby
require 'ostruct'

require 'disposable'
require 'disposable/twin/struct'

require 'reform'
require 'reform/form/active_model/validations'


Reform::Form.class_eval do
  include Reform::Form::ActiveModel::Validations
end


class SongForm < Reform::Form
  property :title

  property :options do
    include Struct
    property :recorded
    property :released

    property :preferences do
      include Struct
      property :show_image
      property :play_teaser
    end
  end
end

song = {
  title: "Seed of Fear and Anger",
  options: {
    recorded: true,
    released: 1,
    preferences: {
      show_image: true,
      play_teaser: 2
    }
  }
}

model = OpenStruct.new(
  options: OpenStruct.new(
    preferences: OpenStruct.new
  ),
)

form = SongForm.new(model)
success = form.validate(song)
puts (success ? 'valid!' : form.errors)
```

Output: 
```
valid!
```

But when
```ruby
model = OpenStruct.new
```
Output
```
 .../reform-2.1.0/lib/reform/form/populator.rb:41:in `handle_fail': [Reform] Your :populator did not return a Reform::Form instance for `options`. (RuntimeError)
   from .../reform-2.1.0/lib/reform/form/populator.rb:26:in `call'
   from .../reform-2.1.0/lib/reform/form/populator.rb:122:in `call'
   from .../representable-3.0.0/lib/representable/pipeline.rb:18:in `evaluate'
   from .../representable-3.0.0/lib/representable/pipeline.rb:10:in `block in call'
   from .../representable-3.0.0/lib/representable/pipeline.rb:9:in `each'
   from .../representable-3.0.0/lib/representable/pipeline.rb:9:in `inject'
   from .../representable-3.0.0/lib/representable/pipeline.rb:9:in `call'
   from .../representable-3.0.0/lib/representable/binding.rb:37:in `uncompile_fragment'
   from .../representable-3.0.0/lib/representable.rb:52:in `block in call'
   from .../representable-3.0.0/lib/representable.rb:50:in `each'
   from .../representable-3.0.0/lib/representable.rb:50:in `call'
   from .../representable-3.0.0/lib/representable.rb:69:in `representable_map!'
   from .../representable-3.0.0/lib/representable.rb:36:in `update_properties_from'
   from .../representable-3.0.0/lib/representable/hash/allow_symbols.rb:10:in `update_properties_from'
   from .../representable-3.0.0/lib/representable/hash.rb:30:in `from_hash'
   from .../reform-2.1.0/lib/reform/form/validate.rb:28:in `deserialize'
   from .../reform-2.1.0/lib/reform/form/validate.rb:21:in `validate'
   from reform_hash_fields.rb:42:in `<main>'
```

**Comment by apotonick** [comment]
Does this work for you?

```ruby
class SongForm < Reform::Form
  property :title

  property :options do
    include Struct
    property :recorded
    property :released

    property :preferences, populate_if_empty: Hash do
      include Struct
      property :show_image
      property :play_teaser
    end
  end
end
```

Explained here: http://trailblazer.to/gems/reform/populator.html

**Comment by sorrat** [comment]
Thanks a lot, Nick!
I have already read about populators, but I could not guess to use Hash with them :)
