### ISSUE TITLE
Getting "can't dup NilClass" with Reform 2.2.0

### ISSUE THREAD

**Issue by simonc** [apotonick/reform#371]
Hi there,

After updating from v2.1 to v2.2 I now get the following error:
```
can't dup NilClass
…/.gem/ruby/2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `dup'
…/.gem/ruby/2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `block in properties'
…/.gem/ruby/2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `each'
…/.gem/ruby/2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `properties'
…/Projects/MyProject/app/forms/some_form.rb:2:in `<class:SomeForm>'
```

The error seems to occur because of the following code:

```ruby
def self.properties(*args)
  options = args.pop if args.last.is_a?(Hash)
  args.each { |name| property(name, options.dup) }
end
```

When no option is provided it tries to call `dup` on `nil` options

Maybe it should be replaced with

```ruby
options = args.last.is_a?(Hash) ? args.pop : {}
```

I can do a PR if no-one is already on it :smile:

**Comment by apotonick** [comment]
Are you doing this? http://trailblazer.to/gems/reform/#rails-support

**Comment by nbulaj** [comment]
@apotonick the same error and `reform-rails` didn't solve it.

Gemfile.lock

```ruby
    reform (2.2.0)
      disposable (>= 0.3.0, < 0.4.0)
      representable (>= 2.4.0, < 3.1.0)
      uber (~> 0.0.11)
    reform-rails (0.1.2)
      activemodel (>= 3.2)
      reform (>= 2.2.0.rc1)
```

Backtrace reference to this concept:

```ruby
class User
  class Profile < Reform::Form
    properties :username, :password
    property :password_confirmation, virtual: true

    validates :username, :password, presence: true
    validates_uniqueness_of :username, case_sensitive: false
  end
end
```

Trace:

```bash
/home/bulai/.rvm/gems/ruby-2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `dup': can't dup NilClass (TypeError)
	from /home/bulai/.rvm/gems/ruby-2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `block in properties'
	from /home/bulai/.rvm/gems/ruby-2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `each'
	from /home/bulai/.rvm/gems/ruby-2.3.1/gems/reform-2.2.0/lib/reform/contract.rb:33:in `properties'
	from /home/bulai/projects/sd2labs/rap_shared_services/app/concepts/user/contracts/profile.rb:3:in `<class:Profile>'
```

**Comment by simonc** [comment]
I confirm, `reform-rails` doesn't change anything :wink:

**Comment by apotonick** [comment]
I could swear I fixed this a few weeks back! I'll look into it tomorrow morning.

The RC has been out for 4 days, but as always, no one tests it, so my strategy for the last 2 years is to release the stable version to force people to test it. 😜

**Comment by simonc** [comment]
Well in the meantime I replaced all my calls to `properties` by a list of calls to `property` as a workaround.

**Comment by apotonick** [comment]
AAaaaaah, I understand now, @simonc ! Send the PR! <3

**Comment by simonc** [comment]
Let's go then! :wink:

**Comment by simonc** [comment]
It took me some time to get the specs right but here it is :wink:

**Comment by apotonick** [comment]
2.2.1 released, thanks so much! :heart:

**Comment by apotonick** [comment]
And, awesome work on the specs! :+1:

**Comment by simonc** [comment]
Glad I could help :wink:
